import type { FAQ, Property, Testimonial } from "@/types";

export const properties: Property[] = [
  {
    slug: "palais-riyad-el-fassia",
    name: "Palais Riyad El Fassia",
    category: "palais",
    pricePerNight: 5800,
    capacity: 16,
    bedrooms: 8,
    bathrooms: 8,
    rating: 5.0,
    reviews: 39,
    featured: true,
    images: [
      "/images/hebergements/palais-riyad-el-fassia-1.jpg",
      "/images/hebergements/palais-riyad-el-fassia-2.jpg",
      "/images/hebergements/palais-riyad-el-fassia-3.jpg",
    ],
  },
  {
    slug: "riad-al-manar",
    name: "Riad Al Manar",
    category: "riad",
    pricePerNight: 1450,
    capacity: 8,
    bedrooms: 4,
    bathrooms: 4,
    rating: 4.9,
    reviews: 128,
    featured: true,
    images: [
      "/images/hebergements/riad-al-manar-1.jpg",
      "/images/hebergements/riad-al-manar-2.jpg",
      "/images/hebergements/riad-al-manar-3.jpg",
    ],
  },
  {
    slug: "riad-jasmin",
    name: "Riad Jasmin",
    category: "riad",
    pricePerNight: 1150,
    capacity: 6,
    bedrooms: 3,
    bathrooms: 3,
    rating: 4.8,
    reviews: 94,
    images: [
      "/images/hebergements/riad-jasmin-1.jpg",
      "/images/hebergements/riad-jasmin-2.jpg",
      "/images/hebergements/riad-jasmin-3.jpg",
    ],
  },
  {
    slug: "villa-atlas-view",
    name: "Villa Atlas View",
    category: "villa",
    pricePerNight: 3200,
    capacity: 12,
    bedrooms: 6,
    bathrooms: 6,
    rating: 5.0,
    reviews: 61,
    featured: true,
    images: [
      "/images/hebergements/villa-atlas-view-1.jpg",
      "/images/hebergements/villa-atlas-view-2.jpg",
      "/images/hebergements/villa-atlas-view-3.jpg",
    ],
  },
  {
    slug: "villa-palmeraie-dune",
    name: "Villa Palmeraie Dune",
    category: "villa",
    pricePerNight: 2600,
    capacity: 10,
    bedrooms: 5,
    bathrooms: 5,
    rating: 4.9,
    reviews: 47,
    images: [
      "/images/hebergements/villa-palmeraie-dune-1.jpg",
      "/images/hebergements/villa-palmeraie-dune-2.jpg",
      "/images/hebergements/villa-palmeraie-dune-3.jpg",
    ],
  },
  {
    slug: "appartement-gueliz-loft",
    name: "Appartement Guéliz Loft",
    category: "appartement",
    pricePerNight: 650,
    capacity: 4,
    bedrooms: 2,
    bathrooms: 2,
    rating: 4.7,
    reviews: 152,
    images: [
      "/images/hebergements/appartement-gueliz-loft-1.jpg",
      "/images/hebergements/appartement-gueliz-loft-2.jpg",
      "/images/hebergements/appartement-gueliz-loft-3.jpg",
    ],
  },
  {
    slug: "appartement-medina-suite",
    name: "Appartement Médina Suite",
    category: "appartement",
    pricePerNight: 780,
    capacity: 3,
    bedrooms: 1,
    bathrooms: 1,
    rating: 4.8,
    reviews: 76,
    images: [
      "/images/hebergements/appartement-medina-suite-1.jpg",
      "/images/hebergements/appartement-medina-suite-2.jpg",
      "/images/hebergements/appartement-medina-suite-3.jpg",
    ],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Camille & Thomas",
    rating: 5,
    service: "Riad Al Manar",
    platform: "airbnb",
  },
  {
    id: "t2",
    name: "Marco Bellini",
    rating: 5,
    service: "Villa Atlas View",
    platform: "booking",
    score: 9.6,
  },
  {
    id: "t3",
    name: "Sarah Al-Farsi",
    rating: 5,
    service: "Riad Jasmin",
    platform: "agoda",
    score: 9.0,
  },
  {
    id: "t4",
    name: "Julien Moreau",
    rating: 4,
    service: "Appartement Guéliz Loft",
    platform: "airbnb",
  },
  {
    id: "t5",
    name: "Amira & Karim Haddad",
    rating: 5,
    service: "Palais Riyad El Fassia",
    platform: "booking",
    score: 10,
  },
  {
    id: "t6",
    name: "Laura Bianchi",
    rating: 5,
    service: "Villa Palmeraie Dune",
    platform: "agoda",
    score: 9.4,
  },
  {
    id: "t7",
    name: "David & Rachel Cohen",
    rating: 5,
    service: "Appartement Médina Suite",
    platform: "airbnb",
  },
  {
    id: "t8",
    name: "Sophie Lambert",
    rating: 5,
    service: "Palais Riyad El Fassia",
    platform: "airbnb",
  },
  {
    id: "t9",
    name: "Ahmed Ben Youssef",
    rating: 5,
    service: "Appartement Guéliz Loft",
    platform: "booking",
    score: 9.4,
  },
  {
    id: "t10",
    name: "Isabella Rossi",
    rating: 4,
    service: "Villa Atlas View",
    platform: "agoda",
    score: 8.4,
  },
];

export const faqs: FAQ[] = [
  { id: "f1" },
  { id: "f2" },
  { id: "f3" },
  { id: "f4" },
  { id: "f5" },
];
